spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/intelligent_switch?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: IntelligentSwitchScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.simpl.RAMJobStore
            misfireThreshold: 60000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
server:
  port: 8080
